# Generated by Django 5.0.7 on 2024-08-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_didescategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didescategory',
            name='ip_address',
            field=models.URLField(blank=True, null=True, verbose_name='Διεύθυνση IP'),
        ),
    ]
