# Generated by Django 5.0.7 on 2024-08-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_didescategory_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='didescategory',
            options={'verbose_name': 'ΔΙΔΕΣ', 'verbose_name_plural': 'ΔΙΔΕΣ'},
        ),
        migrations.AlterField(
            model_name='didescategory',
            name='category',
            field=models.CharField(choices=[('unclassified', 'Αδιαβάθμητο Δίκτυο DCE'), ('classified', 'Διαβαθμισμένο Δίκτυο DTE')], max_length=20, verbose_name='Κατηγορία'),
        ),
    ]
