# Generated by Django 5.0.6 on 2024-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_officerservicereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('ΣΤΡ(ΔΒ)', 'ΣΤΡ(ΔΒ)'), ('ΕΣΣΟ Κατάταξης', 'ΕΣΣΟ Κατάταξης'), ('ΑΣΜ', 'ΑΣΜ')], max_length=50, verbose_name='Βαθμός')),
                ('enlistment_esso', models.CharField(max_length=50, verbose_name='ΕΣΣΟ Κατάταξης')),
                ('last_name', models.CharField(max_length=100, verbose_name='Επώνυμο')),
                ('first_name', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('discharge_date', models.DateField(verbose_name='Ημερομηνία Απολύσεως')),
            ],
            options={
                'verbose_name': 'Στρατιώτης',
                'verbose_name_plural': 'Στρατιώτες',
            },
        ),
    ]
