# Generated by Django 5.0.6 on 2024-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_soldier'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='asm',
            field=models.CharField(default=0, max_length=50, verbose_name='ΑΣΜ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank',
            field=models.CharField(choices=[('ΣΤΡ(ΔΒ)', 'ΣΤΡ(ΔΒ)')], max_length=50, verbose_name='Βαθμός'),
        ),
    ]
