# Generated by Django 5.0.6 on 2024-08-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_soldier_asm_alter_soldier_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Περιοχή'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Τόπος Γέννησης'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Έτος Γέννησης'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ομάδα Αίματος'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='concerns',
            field=models.TextField(blank=True, null=True, verbose_name='Προβλήματα που απασχολούν'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='economic_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Οικονομική Κατάσταση'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Γραμματικές Γνώσεις'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα Πατέρα'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επάγγελμα Πατέρα'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='foreign_languages',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ξένες Γλώσσες'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='health_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Κατάσταση Υγείας'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='leaves',
            field=models.TextField(blank=True, null=True, verbose_name='Άδειες'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Οικογενειακή Κατάσταση'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα Μητέρας'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επάγγελμα Μητέρας'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επάγγελμα'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='origin_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Τόπος Καταγωγής'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='penalties',
            field=models.TextField(blank=True, null=True, verbose_name='Ποινές'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='phone_number_home',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Σταθερό Τηλέφωνο'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='phone_number_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Κινητό Τηλέφωνο'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='physical_ability',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Σωματική Ικανότητα'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='relative_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλέφωνο Συγγενών'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='relative_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ιδιότητα Συγγενή'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='residence_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Τόπος Διαμονής'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='service_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Διάρκεια θητείας (μήνες)'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='siblings_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Αριθμός Αδελφών'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='special_skills',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ειδικές Γνώσεις'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Οδός'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Αριθμός'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='unit_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημ. Εισόδου στην Μονάδα'),
        ),
    ]
