# Generated by Django 5.0.7 on 2024-08-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_soldier_area_soldier_birth_place_soldier_birth_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
            ],
        ),
    ]
