# Generated by Django 5.0.6 on 2024-08-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('informed_by_commander_kepik', models.BooleanField(default=False, verbose_name='Ενημερώθηκα απο τον Διοικητή ΚΕΠΙΚ')),
                ('informed_by_company_commander', models.BooleanField(default=False, verbose_name='Ενημερώθηκα από τον Διοικητή Λόχου')),
                ('informed_by_unit_commander', models.BooleanField(default=False, verbose_name='Ενημερώθηκα από τον Διοικητή Μονάδας')),
                ('received_keys', models.BooleanField(default=False, verbose_name='Παρελήφθησαν τα κλειδιά της κλειδοθήκης ΑΞΥΠ ΚΕΠΙΚ')),
                ('phone_service_soldier', models.CharField(max_length=100, verbose_name='Οπλίτης σε υπηρεσία')),
                ('phone_check_done', models.BooleanField(default=False, verbose_name='Έγινε τηλεφωνικός έλεγχος τις προβλεπόμενες ώρες')),
                ('reported_interruptions', models.TextField(blank=True, verbose_name='Διακοπές που αναφέρθηκαν')),
                ('causes_and_duration', models.TextField(blank=True, verbose_name='Αίτια και διάρκεια διακοπών')),
                ('restoration_actions', models.TextField(blank=True, verbose_name='Ενέργειες αποκατάστασης διακοπών')),
                ('restored_interruptions', models.TextField(blank=True, verbose_name='Διακοπές που αποκαταστήθηκαν')),
                ('teletype_service_soldier', models.CharField(max_length=100, verbose_name='Οπλίτης σε υπηρεσία')),
                ('system_operation_sda_pyrseia', models.TextField(blank=True, verbose_name='ΣΔΑ - ΠΥΡΣΕΙΑ')),
                ('system_operation_aifs', models.TextField(blank=True, verbose_name='AIFS')),
                ('system_operation_cronos', models.TextField(blank=True, verbose_name='CRONOS')),
                ('fault_restoration_actions', models.TextField(blank=True, verbose_name='Ενέργειες αποκατάστασης βλαβών (αν υπάρχουν)')),
            ],
        ),
    ]
