# Generated by Django 5.0.6 on 2024-08-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='phone_service_soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_service', to='myapp.soldier', verbose_name='Οπλίτης σε υπηρεσία'),
        ),
        migrations.AlterField(
            model_name='report',
            name='teletype_service_soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teletype_service', to='myapp.soldier', verbose_name='Οπλίτης σε υπηρεσία'),
        ),
    ]
