# Generated by Django 5.0.7 on 2024-08-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_report_phone_service_soldier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='applications_check_done',
            field=models.BooleanField(default=False, verbose_name='Έγινε έλεγχος των εφαρμογών του ΚΕΠΙΚ/ΓΕΣ μέσω των υπερσυνδέσμων ανά τρίωρο'),
        ),
        migrations.AddField(
            model_name='report',
            name='applications_problem_found',
            field=models.TextField(blank=True, verbose_name='Πρόβλημα που διαπιστώθηκε'),
        ),
        migrations.AddField(
            model_name='report',
            name='network_check_done',
            field=models.BooleanField(default=False, verbose_name='Έγινε έλεγχος του δικτύου (ΔΙΔΕΣ, NS WAN, ΑΔΜΕ) μέσω των εποπτικών εργαλείων ανά τρίωρο'),
        ),
        migrations.AddField(
            model_name='report',
            name='network_problem_found',
            field=models.TextField(blank=True, verbose_name='Πρόβλημα που διαπιστώθηκε'),
        ),
        migrations.AddField(
            model_name='report',
            name='servers_check_done',
            field=models.BooleanField(default=False, verbose_name='Έγινε έλεγχος των εξυπηρετητών του ΚΕΠΙΚ/ΓΕΣ μέσω των εποπτικών εργαλείων ανά τρίωρο'),
        ),
        migrations.AddField(
            model_name='report',
            name='servers_problem_found',
            field=models.TextField(blank=True, verbose_name='Πρόβλημα που διαπιστώθηκε'),
        ),
        migrations.AddField(
            model_name='report',
            name='vosip_check_done',
            field=models.BooleanField(default=False, verbose_name='Έγινε έλεγχος των τηλεφώνων VOSIP μέσω των εποπτικών εργαλείων ανά τρίωρο'),
        ),
        migrations.AddField(
            model_name='report',
            name='vosip_problem_found',
            field=models.TextField(blank=True, verbose_name='Πρόβλημα που διαπιστώθηκε'),
        ),
    ]
