# Generated by Django 5.0.6 on 2024-08-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_report_applications_check_done_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
