# Generated by Django 5.0.7 on 2024-08-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxypKepikServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='reports/')),
            ],
        ),
    ]
