# Generated by Django 5.0.7 on 2024-08-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_axypkepikservicereport_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OplitiServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='opliti_reports/')),
            ],
        ),
    ]
