# Generated by Django 5.0.6 on 2024-09-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_oplitiservicereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxypCodesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Server/PC, Εφαρμογή')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Παρατηρήσεις')),
            ],
            options={
                'verbose_name': 'Κωδικός ΑΞΥΠ',
                'verbose_name_plural': 'Κωδικοί ΑΞΥΠ',
            },
        ),
    ]
