# Generated by Django 5.0.6 on 2024-09-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_axypcodescategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axypcodescategory',
            name='category',
        ),
        migrations.AddField(
            model_name='axypcodescategory',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλέφωνο Επικοινωνίας'),
        ),
        migrations.AddField(
            model_name='axypcodescategory',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Περιγραφή'),
        ),
        migrations.AddField(
            model_name='axypcodescategory',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα'),
        ),
        migrations.AddField(
            model_name='axypcodescategory',
            name='item_type',
            field=models.CharField(blank=True, choices=[('computers', 'ΥΠΟΛΟΓΙΣΤΕΣ'), ('pyrseia', 'ΠΥΡΣΕΙΑ'), ('applications', 'ΛΟΙΠΕΣ ΕΦΑΡΜΟΓΕΣ'), ('staff', 'ΣΤΕΛΕΧΗ'), ('useful_phones', 'ΧΡΗΣΙΜΑ ΤΗΛΕΦΩΝΑ'), ('phone_codes', 'ΚΩΔΙΚΟΙ ΛΕΙΤΟΥΡΓΙΑΣ ΤΗΛΕΦΩΝΟΥ')], max_length=50, null=True, verbose_name='ΕΙΔΟΣ'),
        ),
        migrations.AddField(
            model_name='axypcodescategory',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επώνυμο'),
        ),
        migrations.AddField(
            model_name='axypcodescategory',
            name='phone_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Κωδικός'),
        ),
        migrations.AddField(
            model_name='axypcodescategory',
            name='phone_function',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Λειτουργία'),
        ),
        migrations.AddField(
            model_name='axypcodescategory',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόστο'),
        ),
        migrations.AddField(
            model_name='axypcodescategory',
            name='server_pc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Server/PC'),
        ),
        migrations.AlterField(
            model_name='axypcodescategory',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='axypcodescategory',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
    ]
