# Generated by Django 5.0.6 on 2024-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_axypcodescategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('total_sda', models.IntegerField()),
                ('total_aifs', models.IntegerField()),
                ('total_cronos', models.IntegerField()),
                ('total_general', models.IntegerField()),
            ],
        ),
    ]
