# Generated by Django 5.0.7 on 2024-09-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_servicereportsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImerisioDinamologio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('night', models.CharField(blank=True, max_length=100, null=True)),
                ('change', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.CharField(blank=True, max_length=100, null=True)),
                ('to_date', models.CharField(blank=True, max_length=100, null=True)),
                ('cleaning', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.soldier')),
            ],
        ),
    ]
