# Generated by Django 5.0.7 on 2024-09-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_imerisiodinamologio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImerisioDinamologio',
        ),
    ]
