# Generated by Django 5.0.7 on 2024-09-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_klistotilefoniko_axypcodesapplications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VOSIPTelephoneDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.IntegerField()),
                ('formation', models.CharField(max_length=255)),
                ('formation_aa', models.IntegerField()),
                ('respondent', models.CharField(max_length=255)),
                ('sip_number', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Κατάλογος | VOSIP',
                'verbose_name_plural': 'Κατάλογος | VOSIP',
            },
        ),
        migrations.AlterModelOptions(
            name='klistotilefoniko',
            options={'verbose_name': 'Κατάλογος | Κλειστό Τηλεφωνικό', 'verbose_name_plural': 'Κατάλογος | Κλειστό Τηλεφωνικό'},
        ),
    ]
