# Generated by Django 5.0.7 on 2024-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_vosiptelephonedirectory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admecategory',
            options={'verbose_name': 'Πεδία Ελέγχου | ΑΔΜΕ', 'verbose_name_plural': 'Πεδία Ελέγχου | ΑΔΜΕ'},
        ),
        migrations.AlterModelOptions(
            name='axypcodesapplications',
            options={'verbose_name': 'Κωδικοί ΑΞΥΠ | Λοιπές Εφαρμογές', 'verbose_name_plural': 'Κωδικοί ΑΞΥΠ | Λοιπές Εφαρμογές'},
        ),
        migrations.AlterModelOptions(
            name='axypcodescategory',
            options={'verbose_name': 'Κωδικοί ΑΞΥΠ | Όλοι', 'verbose_name_plural': 'Κωδικοί ΑΞΥΠ | Όλοι'},
        ),
        migrations.AlterModelOptions(
            name='axypcodescomputers',
            options={'verbose_name': 'Κωδικοί ΑΞΥΠ | Υπολογιστές', 'verbose_name_plural': 'Κωδικοί ΑΞΥΠ | Υπολογιστές'},
        ),
        migrations.AlterModelOptions(
            name='axypcodesphonecodes',
            options={'verbose_name': 'Κωδικοί ΑΞΥΠ | Κωδικοί Λειτουργίας Τηλεφώνου', 'verbose_name_plural': 'Κωδικοί ΑΞΥΠ | Κωδικοί Λειτουργίας Τηλεφώνου'},
        ),
        migrations.AlterModelOptions(
            name='axypcodespyrseia',
            options={'verbose_name': 'Κωδικοί ΑΞΥΠ | Πυρσεία', 'verbose_name_plural': 'Κωδικοί ΑΞΥΠ | Πυρσεία'},
        ),
        migrations.AlterModelOptions(
            name='axypcodesstaff',
            options={'verbose_name': 'Κωδικοί ΑΞΥΠ | Στελέχη', 'verbose_name_plural': 'Κωδικοί ΑΞΥΠ | Στελέχη'},
        ),
        migrations.AlterModelOptions(
            name='axypcodesusefulphones',
            options={'verbose_name': 'Κωδικοί ΑΞΥΠ | Χρήσιμα Τηλέφωνα', 'verbose_name_plural': 'Κωδικοί ΑΞΥΠ | Χρήσιμα Τηλέφωνα'},
        ),
        migrations.AlterModelOptions(
            name='axypkepikservicereport',
            options={'verbose_name': 'Αναφορά | Αναφορά Αξιωματικού Υπηρεσίας', 'verbose_name_plural': 'Αναφορές | Αναφορές Αξιωματικού Υπηρεσίας'},
        ),
        migrations.AlterModelOptions(
            name='didescategory',
            options={'verbose_name': 'Πεδία Ελέγχου | ΔΙΔΕΣ', 'verbose_name_plural': 'Πεδία Ελέγχου | ΔΙΔΕΣ'},
        ),
        migrations.AlterModelOptions(
            name='harpcategory',
            options={'verbose_name': 'Πεδία Ελέγχου | HARP', 'verbose_name_plural': 'Πεδία Ελέγχου | HARP'},
        ),
        migrations.AlterModelOptions(
            name='officerservicereport',
            options={'verbose_name': 'Οργάνωση | Αξιωματικός Υπηρεσίας ΚΕΠΙΚ', 'verbose_name_plural': 'Οργάνωση | Αξιωματικοί Υπηρεσίας ΚΕΠΙΚ'},
        ),
        migrations.AlterModelOptions(
            name='oplitiservicereport',
            options={'verbose_name': 'Αναφορά | Αναφορά Οπλίτη Υπηρεσίας', 'verbose_name_plural': 'Αναφορές | Αναφορές Οπλιτών Υπηρεσίας'},
        ),
        migrations.AlterModelOptions(
            name='soldier',
            options={'verbose_name': 'Οργάνωση | Στρατιώτης', 'verbose_name_plural': 'Οργάνωση | Στρατιώτες'},
        ),
        migrations.RenameField(
            model_name='vosiptelephonedirectory',
            old_name='formation',
            new_name='epiteleio_sximatismos',
        ),
        migrations.RenameField(
            model_name='vosiptelephonedirectory',
            old_name='respondent',
            new_name='xristis_arithmou_vosip',
        ),
        migrations.RemoveField(
            model_name='vosiptelephonedirectory',
            name='aa',
        ),
        migrations.RemoveField(
            model_name='vosiptelephonedirectory',
            name='device',
        ),
        migrations.RemoveField(
            model_name='vosiptelephonedirectory',
            name='formation_aa',
        ),
        migrations.RemoveField(
            model_name='vosiptelephonedirectory',
            name='sip_number',
        ),
        migrations.AddField(
            model_name='vosiptelephonedirectory',
            name='paratiriseis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
