# Generated by Django 5.0.7 on 2024-09-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_admecategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vosiptelephonedirectory',
            old_name='xristis_arithmou_vosip',
            new_name='xristis',
        ),
        migrations.AddField(
            model_name='vosiptelephonedirectory',
            name='arithmos_vosip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
