# Generated by Django 5.0.7 on 2024-09-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_rename_xristis_arithmou_vosip_vosiptelephonedirectory_xristis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vosiptelephonedirectory',
            name='arithmos_vosip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
