# Generated by Django 5.0.7 on 2024-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_vosiptelephonedirectory_arithmos_vosip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HARPDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiteleio_sximatismos', models.CharField(max_length=255, verbose_name='Επιτελείο - Σχηματισμός')),
                ('aa_ana_sximatismo', models.CharField(max_length=255, verbose_name='Α/Α ανα σχηματισμό')),
                ('antapokritis', models.CharField(max_length=255, verbose_name='Ανταποκριτής')),
                ('arithmos_sip', models.CharField(max_length=20, verbose_name='Αριθμός SIP')),
                ('syskeyi', models.CharField(max_length=100, verbose_name='Συσκευή')),
            ],
            options={
                'verbose_name': 'Κατάλογος | HARP',
                'verbose_name_plural': 'Κατάλογος | HARP',
            },
        ),
        migrations.AlterField(
            model_name='vosiptelephonedirectory',
            name='arithmos_vosip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Αριθμός VoSIP'),
        ),
        migrations.AlterField(
            model_name='vosiptelephonedirectory',
            name='epiteleio_sximatismos',
            field=models.CharField(choices=[('ΓΕΕΘΑ/ΔΕΠ', 'ΓΕΕΘΑ/ΔΕΠ'), ('ΓΕΣ', 'ΓΕΣ'), ('1 ΣΤΡΑΤΙΑ', '1 ΣΤΡΑΤΙΑ'), ('ΑΣΔΕΝ', 'ΑΣΔΕΝ'), ('ΑΣΔΥΣ', 'ΑΣΔΥΣ'), ('Γ΄ ΣΣ', 'Γ΄ ΣΣ'), ('Δ΄ ΣΣ', 'Δ΄ ΣΣ'), ('Ι ΜΠ', 'Ι ΜΠ'), ('ΔΔΕΕ', 'ΔΔΕΕ'), ('ΙΙ Μ/Κ ΜΠ', 'ΙΙ Μ/Κ ΜΠ'), ('XII M/K MΠ', 'XII M/K MΠ'), ('XVI M/K MΠ', 'XVI M/K MΠ'), ('ΧΧ ΤΘΜ', 'ΧΧ ΤΘΜ'), ('95 ΑΔΤΕ', '95 ΑΔΤΕ'), ('98 ΑΔΤΕ', '98 ΑΔΤΕ'), ('3 Μ/Κ ΤΑΞ', '3 Μ/Κ ΤΑΞ'), ('7 Μ/Κ ΤΑΞ', '7 Μ/Κ ΤΑΞ'), ('30 Μ/Κ ΤΑΞ', '30 Μ/Κ ΤΑΞ'), ('31 Μ/Κ ΤΑΞ', '31 Μ/Κ ΤΑΞ'), ('33 Μ/Κ ΤΑΞ', '33 Μ/Κ ΤΑΞ'), ('34 Μ/Κ ΤΑΞ', '34 Μ/Κ ΤΑΞ'), ('50 Μ/Κ ΤΑΞ', '50 Μ/Κ ΤΑΞ'), ('8 Μ/Π ΤΑΞ', '8 Μ/Π ΤΑΞ'), ('9 Μ/Π ΤΑΞ', '9 Μ/Π ΤΑΞ'), ('29 Μ/Π ΤΑΞ', '29 Μ/Π ΤΑΞ'), ('5 ΤΑΞΠΖ', '5 ΤΑΞΠΖ'), ('1 ΤΑΞΚΔ-ΑΛ', '1 ΤΑΞΚΔ-ΑΛ'), ('32 ΤΑΞΠΝ', '32 ΤΑΞΠΝ'), ('71 Α/Μ ΤΑΞ', '71 Α/Μ ΤΑΞ'), ('ΧΧΙ ΤΘΤ', 'ΧΧΙ ΤΘΤ'), ('ΧΧΙΙΙ ΤΘΤ', 'ΧΧΙΙΙ ΤΘΤ'), ('ΧΧΙV ΤΘΤ', 'ΧΧΙV ΤΘΤ'), ('ΧΧV ΤΘΤ', 'ΧΧV ΤΘΤ'), ('1Η ΤΑΞΑΣ', '1Η ΤΑΞΑΣ'), ('79 ΑΔΤΕ', '79 ΑΔΤΕ'), ('80 ΑΔΤΕ', '80 ΑΔΤΕ'), ('96 ΑΔΤΕ', '96 ΑΔΤΕ'), ('88 ΣΔΙ', '88 ΣΔΙ'), ('ΤΔ/21 Μ/Κ ΣΠ', 'ΤΔ/21 Μ/Κ ΣΠ'), ('ΤΔ/41 ΣΠ', 'ΤΔ/41 ΣΠ'), ('1 ΣΠ', '1 ΣΠ'), ('10 ΣΠ', '10 ΣΠ'), ('15 ΣΠ', '15 ΣΠ'), ('ΕΛΔΥΚ', 'ΕΛΔΥΚ'), ('487 ΤΔΒ', '487 ΤΔΒ')], max_length=255, verbose_name='Επιτελείο - Σχηματισμός'),
        ),
        migrations.AlterField(
            model_name='vosiptelephonedirectory',
            name='paratiriseis',
            field=models.TextField(blank=True, null=True, verbose_name='Παρατηρήσεις'),
        ),
        migrations.AlterField(
            model_name='vosiptelephonedirectory',
            name='xristis',
            field=models.CharField(max_length=255, verbose_name='Χρήστης'),
        ),
    ]
