# Generated by Django 5.0.7 on 2024-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_harpdirectory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harpdirectory',
            name='aa_ana_sximatismo',
            field=models.CharField(max_length=255, verbose_name='Α/Α (ανα σχηματισμό)'),
        ),
        migrations.AlterField(
            model_name='harpdirectory',
            name='arithmos_sip',
            field=models.CharField(max_length=255, verbose_name='Αριθμός SIP'),
        ),
        migrations.AlterField(
            model_name='harpdirectory',
            name='epiteleio_sximatismos',
            field=models.CharField(choices=[('ΥΠΕΘΑ', 'ΥΠΕΘΑ'), ('ΓΕΕΘΑ', 'ΓΕΕΘΑ'), ('ΓΕΣ', 'ΓΕΣ'), ('1η ΣΤΡΑΤΙΑ', '1η ΣΤΡΑΤΙΑ'), ('ΓΣΣ', 'ΓΣΣ'), ('ΔΣΣ', 'ΔΣΣ'), ('ΑΣΔΕΝ', 'ΑΣΔΕΝ'), ('ΑΣΔΥΣ', 'ΑΣΔΥΣ'), ('I ΜΠ', 'I ΜΠ'), ('ΓΕΝ', 'ΓΕΝ'), ('ΓΕΑ', 'ΓΕΑ')], max_length=255, verbose_name='Επιτελείο - Σχηματισμός'),
        ),
        migrations.AlterField(
            model_name='harpdirectory',
            name='syskeyi',
            field=models.CharField(max_length=255, verbose_name='Συσκευή'),
        ),
    ]
