# Generated by Django 5.0.7 on 2024-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_harpdirectory_aa_ana_sximatismo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klistotilefoniko',
            name='category',
            field=models.CharField(choices=[('ΥΠΕΘΑ', 'ΥΠΕΘΑ'), ('ΓΕΕΘΑ', 'ΓΕΕΘΑ'), ('ΓΕΣ', 'ΓΕΣ'), ('ΓΕΝ', 'ΓΕΝ'), ('ΓΕΑ', 'ΓΕΑ'), ('ΚΥΠΡΟΣ', 'ΚΥΠΡΟΣ')], max_length=10, verbose_name='Κατηγορία'),
        ),
    ]
