# Generated by Django 5.0.7 on 2024-09-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_klistotilefoniko_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='area',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='concerns',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='discharge_date',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='economic_status',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='education',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='enlistment_esso',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='foreign_languages',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='leaves',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='mother_occupation',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='origin_place',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='penalties',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='phone_number_home',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='phone_number_mobile',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='physical_ability',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='relative_phone',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='relative_relation',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='residence_place',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='service_duration',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='siblings_number',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='special_skills',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='street',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='unit_entry_date',
        ),
        migrations.AddField(
            model_name='soldier',
            name='adeies',
            field=models.TextField(blank=True, null=True, verbose_name='ΑΔΕΙΕΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='arithmos_adelfon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΑΡΙΘΜΟΣ ΑΔΕΛΦΩΝ – ΦΥΛΛΟ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='deksiotites',
            field=models.TextField(blank=True, null=True, verbose_name='ΔΕΞΙΟΤΗΤΕΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='diarkeia_thiteias',
            field=models.IntegerField(blank=True, null=True, verbose_name='ΔΙΑΡΚΕΙΑ ΘΗΤΕΙΑΣ (ΜΗΝΕΣ)'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='eidikes_grammatikes_gnoseis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ΕΙΔΙΚΕΣ ΓΝΩΣΕΙΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='epaggelma_mitros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΕΠΑΓΓΕΛΜΑ ΜΗΤΕΡΑΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='epaggelma_patros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΕΠΑΓΓΕΛΜΑ ΠΑΤΕΡΑ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='epaggelma_politis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΕΠΑΓΓΕΛΜΑ ΩΣ ΠΟΛΙΤΗΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='eponymo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΕΠΩΝΥΜΟ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='esso_katataksis',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ΕΣΣΟ ΚΑΤΑΤΑΞΗΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='etos_genniseos',
            field=models.IntegerField(blank=True, null=True, verbose_name='ΕΤΟΣ ΓΕΝΝΗΣΕΩΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='genikes_paratiriseis',
            field=models.TextField(blank=True, null=True, verbose_name='ΓΕΝΙΚΕΣ ΠΑΡΑΤΗΡΗΣΕΙΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='grammatikes_gnoseis',
            field=models.CharField(blank=True, choices=[('Απόφοιτος Λυκείου', 'Απόφοιτος Λυκείου'), ('Απόφοιτος ΑΕΙ', 'Απόφοιτος ΑΕΙ'), ('Απόφοιτος ΤΕΙ', 'Απόφοιτος ΤΕΙ'), ('Ενεργός ΑΕΙ', 'Ενεργός ΑΕΙ'), ('Ενεργός ΤΕΙ', 'Ενεργός ΤΕΙ'), ('Απόφοιτος ΙΕΚ', 'Απόφοιτος ΙΕΚ'), ('Ενεργός ΙΕΚ', 'Ενεργός ΙΕΚ')], max_length=50, null=True, verbose_name='ΓΡΑΜΜΑΤΙΚΕΣ ΓΝΩΣΕΙΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='imerominia_apolysis',
            field=models.DateField(blank=True, null=True, verbose_name='ΗΜ. ΑΠΟΛΥΣΕΩΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='imerominia_eisodou_monada',
            field=models.DateField(blank=True, null=True, verbose_name='ΗΜ. ΕΙΣΟΔΟΥ ΣΤΗΝ ΜΟΝΑΔΑ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='imerominia_strateusis',
            field=models.DateField(blank=True, null=True, verbose_name='ΗΜ. ΣΤΡΑΤΕΥΣΗΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='katastasi_ygeias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΚΑΤΑΣΤΑΣΗ ΥΓΕΙΑΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='odos_arithmos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ΟΔΟΣ ΚΑΙ ΑΡΙΘΜΟΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='oikeiou_sxesi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΣΧΕΣΗ ΜΕ ΤΟΝ ΟΙΚΕΙΟ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='oikogeneiaki_katastasi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΟΙΚΟΓ. ΚΑΤΑΣΤΑΣΗ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='oikonomiki_katastasi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΟΙΚΟΝ. ΚΑΤΑΣΤΑΣΗ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='omada_aimatos',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='ΟΜΑΔΑ ΑΙΜΑΤΟΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='onoma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΟΝΟΜΑ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='onoma_mitros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΟΝΟΜΑ ΜΗΤΕΡΑΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='onoma_patros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΟΝΟΜΑ ΠΑΤΕΡΑ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='paratiriseis_ygeias',
            field=models.TextField(blank=True, null=True, verbose_name='ΠΑΡΑΤΗΡΗΣΕΙΣ ΥΓΕΙΑΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='periochi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΠΕΡΙΟΧΗ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='poines',
            field=models.TextField(blank=True, null=True, verbose_name='ΠΟΙΝΕΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='provlimata_pou_apasxoloun',
            field=models.TextField(blank=True, null=True, verbose_name='ΠΡΟΒΛΗΜΑΤΑ ΠΟΥ ΑΠΑΣΧΟΛΟΥΝ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='somatiki_ikanotita',
            field=models.CharField(blank=True, choices=[('Ι1', 'Ι1'), ('Ι2', 'Ι2'), ('Ι3', 'Ι3'), ('Ι3 Άοπλο', 'Ι3 Άοπλο'), ('Ι4', 'Ι4')], max_length=10, null=True, verbose_name='ΣΩΜΑΤΙΚΗ ΙΚΑΝΟΤΗΤΑ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='tilefono_kinito',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ΤΗΛ. ΚΙΝΗΤΟ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='tilefono_oikeiou',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ΤΗΛΕΦΩΝΟ ΟΙΚΕΙΟΥ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='tilefono_stathero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ΤΗΛ. ΣΤΑΘΕΡΟ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='topos_diamonis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ΤΟΠΟΣ ΔΙΑΜΟΝΗΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='topos_genniseos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ΤΟΠΟΣ ΓΕΝΝΗΣΕΩΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='topos_katagogis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ΤΟΠΟΣ ΚΑΤΑΓΩΓΗΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='vathmos',
            field=models.CharField(blank=True, choices=[('ΣΤΡ(ΔΒ)', 'ΣΤΡ(ΔΒ)'), ('ΣΤΡ(ΠΖ)', 'ΣΤΡ(ΠΖ)'), ('ΣΤΡ(ΠΒ)', 'ΣΤΡ(ΠΒ)'), ('ΣΤΡ(ΤΘ)', 'ΣΤΡ(ΤΘ)'), ('ΣΤΡ(ΠΖ)', 'ΣΤΡ(ΠΖ)')], max_length=10, null=True, verbose_name='ΒΑΘΜΟΣ'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='xenes_glosses',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ΞΕΝΕΣ ΓΛΩΣΣΕΣ'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='asm',
            field=models.PositiveIntegerField(default=0, verbose_name='ΑΣΜ'),
        ),
    ]
