# Generated by Django 5.0.7 on 2024-09-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_soldier_area_remove_soldier_birth_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='iban',
        ),
        migrations.AddField(
            model_name='soldier',
            name='posto',
            field=models.TextField(blank=True, null=True, verbose_name='ΠΟΣΤΟ'),
        ),
    ]
