# Generated by Django 5.0.7 on 2024-09-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_postareport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostaReport',
        ),
    ]
