# Generated by Django 5.0.6 on 2024-10-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_axypkepikservicereport_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axypkepikservicereport',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.officerservicereport'),
        ),
    ]
