# Generated by Django 5.0.6 on 2024-10-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_axypkepikservicereport_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='axypkepikservicereport',
            name='report_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
