# Generated by Django 5.0.6 on 2024-10-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_axypkepikservicereport_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axypkepikservicereport',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='axypkepikservicereport',
            name='report_date',
        ),
        migrations.AlterField(
            model_name='axypkepikservicereport',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
