# Generated by Django 5.0.6 on 2024-10-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_axypkepikservicereport_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='vathmos',
            field=models.CharField(blank=True, choices=[('ΣΤΡ(ΔΒ)', 'ΣΤΡ(ΔΒ)'), ('ΣΤΡ(ΠΖ)', 'ΣΤΡ(ΠΖ)'), ('ΣΤΡ(ΠΒ)', 'ΣΤΡ(ΠΒ)'), ('ΣΤΡ(ΤΘ)', 'ΣΤΡ(ΤΘ)')], max_length=10, null=True, verbose_name='ΒΑΘΜΟΣ'),
        ),
        migrations.CreateModel(
            name='SoldierEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Καταχώρηση')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='myapp.soldier')),
            ],
            options={
                'verbose_name': 'Καταχώρηση Στρατιώτη',
                'verbose_name_plural': 'Καταχωρήσεις Στρατιωτών',
                'unique_together': {('soldier', 'date')},
            },
        ),
    ]
