# Generated by Django 5.0.6 on 2024-10-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_soldier_vathmos_soldierentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldierEntry',
        ),
    ]
