# Generated by Django 5.0.6 on 2024-10-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_spreadsheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spreadsheet',
        ),
    ]
