# Generated by Django 5.0.6 on 2024-10-13 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_delete_spreadsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('service_type', models.CharField(blank=True, choices=[('ΕΞ', 'ΕΞ'), ('ΤΗΠ', 'ΤΗΠ')], max_length=10, null=True)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.soldier')),
            ],
            options={
                'verbose_name': 'Υπηρεσία',
                'verbose_name_plural': 'Υπηρεσίες',
                'unique_together': {('soldier', 'month')},
            },
        ),
    ]
