# Generated by Django 5.0.6 on 2024-10-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
