# Generated by Django 5.0.6 on 2024-10-13 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_type', models.CharField(blank=True, choices=[('ΕΞ', 'ΕΞ'), ('ΤΗΠ', 'ΤΗΠ'), ('ΑΔΕΙΑ', 'ΑΔΕΙΑ'), ('ΑΝΤΑΠΟΚΡΙΣΗ', 'ΑΝΤΑΠΟΚΡΙΣΗ')], max_length=20, null=True)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.soldier')),
            ],
            options={
                'verbose_name': 'Ημερήσια Υπηρεσία',
                'verbose_name_plural': 'Ημερήσιες Υπηρεσίες',
                'unique_together': {('soldier', 'date')},
            },
        ),
    ]
