# Generated by Django 5.0.6 on 2024-10-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_dailyservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErmisDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiteleio_sximatismos', models.CharField(choices=[('ΓΕΕΘΑ - ΓΕΣ', 'ΓΕΕΘΑ - ΓΕΣ'), ('1η ΣΤΡΑΤΙΑ', '1η ΣΤΡΑΤΙΑ'), ('Ι ΜΠ', 'Ι ΜΠ'), ('32 ΤΑΞΠ/Ν', '32 ΤΑΞΠ/Ν'), ('71 Α/Μ ΤΑΞ', '71 Α/Μ ΤΑΞ'), ('1 ΤΑΞΑΣ', '1 ΤΑΞΑΣ'), ('1 ΤΑΞΚΔ-ΑΛ', '1 ΤΑΞΚΔ-ΑΛ'), ('ΙI Μ/Κ ΜΠ', 'ΙI Μ/Κ ΜΠ'), ('33 Μ/Κ ΤΑΞ', '33 Μ/Κ ΤΑΞ'), ('34 Μ/Κ ΤΑΞ', '34 Μ/Κ ΤΑΞ'), ('Γ΄ΣΣ / NDC-GR', 'Γ΄ΣΣ / NDC-GR'), ('8 M/Π ΤΑΞ', '8 M/Π ΤΑΞ'), ('9 ΤΑΞΠΖ', '9 ΤΑΞΠΖ'), ('10 ΣΠ «Χ ΜΠ»', '10 ΣΠ «Χ ΜΠ»'), ('Δ΄ ΣΣ', 'Δ΄ ΣΣ'), ('ΧΙΙ Μ/Κ ΜΠ', 'ΧΙΙ Μ/Κ ΜΠ'), ('7 Μ/Κ ΤΑΞ', '7 Μ/Κ ΤΑΞ'), ('31 Μ/Κ ΤΑΞ', '31 Μ/Κ ΤΑΞ'), ('ΧΧΙΙΙ ΤΘΤ', 'ΧΧΙΙΙ ΤΘΤ'), ('50 Μ/Κ ΤΑΞ', '50 Μ/Κ ΤΑΞ'), ('XVΙ Μ/Κ ΜΠ', 'XVΙ Μ/Κ ΜΠ'), ('3 Μ/Κ ΤΑΞ', '3 Μ/Κ ΤΑΞ'), ('30 Μ/Κ ΤΑΞ', '30 Μ/Κ ΤΑΞ')], max_length=255, verbose_name='Επιτελείο - Σχηματισμός')),
                ('aa_ana_sximatismo', models.CharField(max_length=255, verbose_name='Α/Α (ανα σχηματισμό)')),
                ('antapokritis', models.CharField(max_length=255, verbose_name='Ανταποκριτής')),
                ('arithmos_call', models.CharField(max_length=255, verbose_name='Αριθμός Κλήσεως')),
            ],
            options={
                'verbose_name': 'Κατάλογος | ΣΑΖΜ - ΕΡΜΗΣ',
                'verbose_name_plural': 'Κατάλογος | ΣΑΖΜ - ΕΡΜΗΣ',
            },
        ),
    ]
