# Generated by Django 5.0.6 on 2024-10-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_ermisdirectory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ermisdirectory',
            name='aa_ana_sximatismo',
        ),
    ]
