# Generated by Django 5.0.6 on 2024-10-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_remove_ermisdirectory_aa_ana_sximatismo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ermisdirectory',
            name='katigoria',
            field=models.CharField(default=1, max_length=255, verbose_name='Κατηγορία'),
            preserve_default=False,
        ),
    ]
