# Generated by Django 5.0.6 on 2024-10-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_fctdirectory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YpaspistirioDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antapokritis', models.CharField(max_length=255, verbose_name='Ανταποκριτής')),
                ('arithmos_ypasp', models.CharField(max_length=255, verbose_name='Αριθμός')),
            ],
            options={
                'verbose_name': 'Κατάλογος | Υπασπιστήρια Ιεραρχίας',
                'verbose_name_plural': 'Κατάλογος | Υπασπιστήρια Ιεραρχίας',
            },
        ),
    ]
