# Generated by Django 5.0.6 on 2024-10-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_ypaspistiriodirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeclineDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antapokritis', models.CharField(max_length=255, verbose_name='Ανταποκριτής')),
                ('arithmos_ote', models.CharField(max_length=255, verbose_name='Αριθμός ΟΤΕ')),
                ('arithmos_epsad', models.CharField(max_length=255, verbose_name='Αριθμός ΕΨΑΔ')),
                ('paratiriseis', models.CharField(max_length=255, verbose_name='Παρατηρήσεις')),
            ],
            options={
                'verbose_name': 'Κατάλογος | Secline Plus',
                'verbose_name_plural': 'Κατάλογος | Secline Plus',
            },
        ),
    ]
