# Generated by Django 5.0.6 on 2024-10-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_seclinedirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epiteleio_sximatismos', models.CharField(choices=[('Γενικό Επιτελείο Εθνικής Άμυνας', 'Γενικό Επιτελείο Εθνικής Άμυνας'), ('ΔΕΠ', 'ΔΕΠ'), ('Στρατός Ξηράς', 'Στρατός Ξηράς'), ('Πολεμικό Ναυτικό', 'Πολεμικό Ναυτικό'), ('Πολεμική Αεροπορία', 'Πολεμική Αεροπορία')], max_length=255, verbose_name='Επιτελείο - Σχηματισμός')),
                ('aa_ana_sximatismo', models.CharField(max_length=255, verbose_name='Α/Α (ανα σχηματισμό)')),
                ('klados_ypiresia', models.CharField(max_length=255, verbose_name='Κλάδος - Υπηρεσία')),
                ('thl_syndesh', models.CharField(max_length=255, verbose_name='Αριθμός Τηλεφωνικής Σύνδεσης')),
            ],
            options={
                'verbose_name': 'Κατάλογος | Δίκτυο Έκτακτων Αναγκών',
                'verbose_name_plural': 'Κατάλογος | Δίκτυο Έκτακτων Αναγκών',
            },
        ),
        migrations.AlterModelOptions(
            name='seclinedirectory',
            options={'verbose_name': 'Κατάλογος | Secline Plus-STU II', 'verbose_name_plural': 'Κατάλογος | Secline Plus-STU II'},
        ),
    ]
